import type { Metadata } from "next";
import "./globals.css";

import Navbar from "./Navbar/page";

export const metadata: Metadata = {
  title: "Hutter Cleaning Service",
  description: "Generated by create Claudio Bispo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
          {children}
        </body>
    </html>
  );
}
