import type { Metadata } from "next";
import "./globals.css";

import Navbar from "./Navbar/page";
import Footer from "./Footer/page";

export const metadata: Metadata = {
  title: "Hutter Cleaning Service",
  description: "Generated by create Claudio Bispo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

        <head>
          <meta charSet="UTF-8" />
          <title>Contact</title>
          <script src="https://unpkg.com/react@16/umd/react.development.js"></script>
          <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
          <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
        </head>
      <body>
        <Navbar/>
          {children}
        <Footer/>
        </body>
    </html>
  );
}
